#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore
polybar -r &
picom &
killall conky
conky &
killall nm-applet
nm-applet --indicator &
killall blueman-applet
blueman-applet &
killall cbatticon
cbatticon &

fusermount -uz /media/onedrive0
fusermount -uz /media/onedrive1
rclone mount --vfs-cache-max-size 2G --vfs-cache-mode full --buffer-size 128M --vfs-cache-max-age 120h --vfs-read-chunk-size 8M --daemon vandriv: /media/onedrive0 &
rclone mount --vfs-cache-max-size 4G --vfs-cache-mode full --buffer-size 128M --vfs-cache-max-age 120h --vfs-read-chunk-size 8M --daemon bisdriv: /media/onedrive1 &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           12

bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border Colors
bspc config focused_border_color "#3B3A61"
bspc config normal_border_color "#2A2A45"

bspc config top_padding		35

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a *:*:'Popup' border=off
